name: Check software

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Output Date
        run: date
      - name: Test wfet
        run: wget --version
      - name: Test curl
        run: curl --version


