name: Run Weather Script and Commit Changes

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 AM UTC

jobs:
  run-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone the repository

      - name: Run Weather Script
        run: ./weather.sh  # Ensure weather.sh modifies the YAML or other files as needed

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Automated update by weather.sh"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authenticated token to push changes


